M48
; DRILL file {KiCad 7.0.6} date Sat Oct 21 01:18:37 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-10-21T01:18:37+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C6.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C12.000
%
G90
G05
T1
X140.0Y-85.0
T2
X55.0Y-55.0
X55.0Y-225.0
X225.0Y-55.0
X225.0Y-225.0
T0
M30
