M48
; DRILL file {KiCad 7.0.11} date Wed Mar  6 00:45:10 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-03-06T00:45:10+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1181
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1201
%
G90
G05
T1
X6.2889Y-4.8157
X7.2999Y-4.8157
X7.6732Y-3.6535
X7.6732Y-4.315
T2
X4.5669Y-4.8134
X5.6969Y-4.8134
M30
